[package]
name = "osm_tb"
version = "0.1.0"
edition = "2024"

[workspace]
members = []

[lib]
name = "osm_tb"
path = "src/lib.rs"

[[example]]
name = "async"
path = "examples/async.rs"


[dev-dependencies]
thiserror = "2.0"

[dependencies]
fmt = "0.1.0"
error-chain = "0.12"
reqwest = { version = "0.12", features = ["json"] }
bytes = "1"

#bevy = "0"
#bevy = { version = "0", default-features = false, features = [] }

##   TODO: reduce bevy_wasm.wasm 72.3 MB  Less feature: still 60.3
bevy = { version = "0", default-features = false, features = [
    #"android-game-activity",
    #"android_shared_stdcxx",
    #"animation",
    #"async_executor",
    #"bevy_asset",
    #"bevy_audio",
    #"bevy_color",
    #"bevy_core_pipeline",
    #"bevy_gilrs",
    #"bevy_gizmos",
    #"bevy_gltf",
    #"bevy_input_focus",
    "bevy_log",
    #"bevy_mesh_picking_backend",
    "bevy_pbr",
    #"bevy_picking",
    #"bevy_render",
    #"bevy_scene",
    #"bevy_sprite",
    #"bevy_sprite_picking_backend",
    #"bevy_state",
    #"bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    #"bevy_window",
    "bevy_winit",
    #"custom_cursor",
    #"default_font",
    #"hdr",
    #"multi_threaded",
    #"png",
    #"smaa_luts",
    #"std",
    #"sysinfo_plugin",
    "tonemapping_luts",
    #"vorbis",
    "webgl2",
    #"x11",
] }

bevy_web_asset = "0.11.0"                          # "This is a tiny crate that that adds the ability to load assets from http and https urls. Supports both wasm (web-sys) and native."
bevy_args = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

openstreetmap-api = "0.3" ## openstreetmap-api-rs/example/
csscolorparser = "0.6"
earcutr = "0.4.3"


[target.'cfg(target_arch = "aarch64")'.dev-dependencies]
tokio = { version = "1", features = ["full"] }
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "1.0", features = [
    # Only features sync,macros,io-util,rt,time are supported on wasm.
    ## No net for wasm. Only this:
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
] }

#[target.'cfg(target_arch = "wasm32")'.features]
web-sys = { version = "^0.3.77", features = ["Window", "Response"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0"
wasm-bindgen = "0"


## [target.'cfg(target_arch = "wasm32")'.dependencies]
## bevy = {version = "0.5", default-features = false, features = []}


##   [dev-dependencies]
##   bevy = { version = "0.16", default-features = false, features = [
##     "bevy_asset",
##     "bevy_core_pipeline",
##     "bevy_log",
##     "bevy_sprite",
##     "bevy_window",        # https://github.com/bevyengine/bevy/issues/16568
##     "png",
##     "webgl2",
##     "x11",                # GitHub Actions runners don't have libxkbcommon installed, so can't use Wayland
##   ] }
