[package]
name = "obi"
version = "0.1.0"
edition = "2021"

[dependencies]
## http = "1.0.0"
reqwest = { version = "0.12", features = ["blocking","json"] } # reqwest with JSON parsing support
error-chain = "0.12"