[package]
name = "osm_tb"
version = "0.1.0"
edition = "2024"

[workspace]
members = [

]

[lib]
name = "osm_tb"
path = "src/lib.rs"

[[example]]
name = "async"
path = "examples/async.rs"

[dependencies]
fmt = "0.1.0"
error-chain = "0.12"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
##serde_json = "1.0"

csscolorparser = "0.6"
earcutr = "0.4.3"
bevy = "0"

#osm_tb = "*"

## cargo:rustc-check-cfg=cfg(target_arch,values("loongarch64","mips32r6","mips64r6","csky"))

[target.'cfg(target_arch = "aarch64")'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

# Only features sync,macros,io-util,rt,time are supported on wasm.
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "1.0", features = [
    ## No net for wasm. Only this:
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
] }

#[target.'cfg(target_arch = "wasm32")'.features]
web-sys = { version = "^0.3.77", features = ["Window", "Response"] }
#wasm-bindgen = "0.2"
#wasm-bindgen-futures = "0"
